default: &default
  adapter: postgresql
  timeout: 5000
  username: femboyfans

development:
  <<: *default
  database: femboyfans_development
  host: postgres
  pool: 5

test:
  <<: *default
  database: femboyfans_test
  host: postgres
  pool: 5

<% if Rails.env.production? %>
production:
  <<: *default
  database: femboyfans
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  pool: <%= Sidekiq.server? ? ENV.fetch("DB_WORKER_POOL_SIZE", 5) : ENV.fetch("DB_POOL_SIZE", 5) %>
<% end %>
