name: Checks

on:
  push:
    branches:
      - master
      - dev
      - build-*
  pull_request:
    branches:
      - master
      - dev
      - build-*

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build FemboyFans Image
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          load: true
          tags: femboyfans
          outputs: type=docker,dest=/tmp/femboyfans.tar

      - name: Upload FemboyFans Image
        uses: actions/upload-artifact@v4
        with:
          name: femboyfans
          path: /tmp/femboyfans.tar

      - name: Build DText Image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:lib/dtext_rb"
          cache-from: type=gha
          load: true
          tags: dtext
          outputs: type=docker,dest=/tmp/dtext.tar


      - name: Upload DText Image
        uses: actions/upload-artifact@v4
        with:
          name: dtext
          path: /tmp/dtext.tar

  rubocop:
    runs-on: ubuntu-22.04
    needs: docker-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Load FemboyFans Image
        uses: ./.github/load-docker-image
        with:
          name: femboyfans

      - name: Run Rubocop
        run: $DOCKER_RUN rubocop --format github

  eslint:
    runs-on: ubuntu-22.04
    needs: docker-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Load FemboyFans Image
        uses: ./.github/load-docker-image
        with:
          name: femboyfans

      - name: Run ESLint
        run: $DOCKER_RUN linter

  tests:
    runs-on: ubuntu-22.04
    needs: docker-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Load FemboyFans Image
        uses: ./.github/load-docker-image
        with:
          name: femboyfans

      - name: Create DB
        run: $DOCKER_RUN --entrypoint bin/rails tests db:create

      - name: Load DB Schema
        run: $DOCKER_RUN --entrypoint bin/rails tests db:schema:load

      - name: Run Tests
        run: $DOCKER_RUN tests

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: log/test.log

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: FemboyFans/FemboyFans

  dtext-tests:
    runs-on: ubuntu-22.04
    needs: docker-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Load DText Image
        uses: ./.github/load-docker-image
        with:
          name: dtext

      - name: Run Tests
        run: $DOCKER_RUN dtext bin/rake test
